function out = run_smoke_ann_nsga2()
%% run_smoke_ann_nsga2 - ANN-NSGA-II 冒烟测试（不依赖 Aspen/COM）
%
% 说明:
%   本函数是 `run_smoke_algorithm` 的快捷包装，用于同时跑 NSGA-II 与 ANN-NSGA-II。

    out = run_smoke_algorithm({'NSGA-II', 'ANN-NSGA-II'}, ...
        'Problem', 'zdt1', ...
        'PopulationSize', 40, ...
        'Iterations', 20, ...
        'Verbose', true);
end
